quotes = [
    "Every line of code is a step closer to your goals. Keep coding and don't give up! 💪",
    "Don't let bugs and errors discourage you. Use them as opportunities to learn and improve your debugging skills. 🐛",
    "Remember, even the most experienced developers make mistakes. Keep learning and improving, and you'll get there eventually. 🧑‍💻",
    "Believe in your abilities as a coder. You are capable of solving any problem that comes your way. 💪",
    "Don't compare your progress to others. Focus on your own journey and the improvements you are making. 🏃‍♂️",
    "Celebrate every small win, no matter how small. Every line of code is a step closer to your goals. 🎉",
    "You are not alone in this journey. There is a community of fellow coders who are here to support and encourage you. 🤝",
    "Don't give up! Keep putting in the hard work and dedication, and you will see progress and success in your coding skills. 💪",
    "Every day is an opportunity to learn and grow as a coder. Keep coding and never give up. 🧑‍💻",
    "You got this! Keep pushing through the challenges and obstacles, and you will become a proficient coder eventually. 💪",
    "Every challenge is an opportunity to learn and improve your skills. Embrace the struggle and keep coding! 💪",
    "Don't let setbacks or failures discourage you. Use them as opportunities to learn and grow as a coder. 🧑‍💻",
    "Remember, progress is not a straight line. Keep pushing through the challenges and you'll get there eventually. 🏃‍♂️",
    "Believe in your abilities and your potential as a coder. You are capable of achieving your goals. 💪",
    "Don't compare your progress to others. Focus on your own journey and the improvements you are making. 🏃‍♂️",
    "Celebrate every small accomplishment. Every line of code is a step closer to your goals. 🎉",
    "You are not alone in this journey. There is a community of fellow coders who are here to support and encourage you. 🤝"]
