name: Run Python script

on:
  schedule:

    - cron: '15 7 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Python script
        run: |
          python twitterBot_scratch.py

